### ISSUE TITLE
Beautify README.md

### ISSUE THREAD

**Issue by Parth-Vader** [Parth-Vader/MobOff#21]
1) GIFs could be added.
2) It needs to more attractive - use of emojis, colors etc.
3) Add other links to command line tools - example "awesome" pages.
4) Add badges (https://forthebadge.com/).

**Comment by HariMahi** [comment]
I'm a beginner so explain me how and where to add command line tools

**Comment by HariMahi** [comment]
changes in README are not seen in the main repository

**Comment by mihirg008** [comment]
@HariMahi what do you mean by changes not seen in main repository?

**Comment by HariMahi** [comment]
ya

**Comment by HariMahi** [comment]
The changes that I made in my PR are not seen in the README  of MobOff

**Comment by yash98** [comment]
They will be update when someone with writing permission(@Parth-Vader) to repository commits them.
