### ISSUE TITLE
Browser Extension

### ISSUE THREAD

**Issue by ArpitKubadia** [Parth-Vader/MobOff#22]
Javascript plugin which if you click on when on YouTube, it will automatically copy the url and send `moboff download --link url`. That way, it will all be a seamless process where whenever you want to download a song, you click on the extension and it automatically does the background work. 

It is not possible to run system commands outside the browser so a workaround needs to be used.

**Comment by Parth-Vader** [comment]
@ArpitKubadia 
I have a workaround for this:- 
* Push the song/video URL to a local database - could be as simple as a `txt` file. You can apply a patch to [YoutubeDataCollector](https://github.com/Parth-Vader/YoutubeDataCollector) for this purpose and use it.
* Then use `bash` script which would check for new entries in the database, and run a default `moboff` command.
* This could be automated via a cronjob (for Linux systems) that would check the file every hour.

Does this make sense?

**Comment by ArpitKubadia** [comment]
Thank you, I'll have a look at what you said.

**Comment by CaptainDaVinci** [comment]
What about web scrapping the link from the song entered?

**Comment by Parth-Vader** [comment]
I believe @ArpitKubadia want's to remove the "command line" part of it, but yeah I think searching from the command line and (suppose) fetching top 5 results could be done @CaptainDaVinci. Do you want to come up with a PR for this? A google search led me to [mps-youtube](http://avilpage.com/2014/12/tech-search-play-download-youtube.html) which could help you.

**Comment by CaptainDaVinci** [comment]
Yes, I would like to work on this.

**Comment by Parth-Vader** [comment]
@ArpitKubadia I think this is not doable, closing.
