### ISSUE TITLE
Unable to play the song on device

### ISSUE THREAD

**Issue by CaptainDaVinci** [Parth-Vader/MobOff#26]
The music file could not be opened

**Comment by ArpitKubadia** [comment]
Can you give a bit more details? What phone are you listening it on and what app are you using for it? It worked fine on my phone

**Comment by CaptainDaVinci** [comment]
I am using Moto g5s+ running Android 7,  when I click on the received music file it just shows "no app can perform this action"

**Comment by ArpitKubadia** [comment]
Try going to the music player app, rescanning the device and then see if it shows up.
I am using Rocket player and it works flawlessly, native play music app tends to give some problems sometimes.

**Comment by CaptainDaVinci** [comment]
Tried playing from the download folder, didn't work.

**Comment by yash98** [comment]
Could you give the link of the music you downloaded? If you used `moboff --video` u might have got .mkv file which some players can't play.

**Comment by Parth-Vader** [comment]
@CaptainDaVinci Try opening the file from the music player (Play Music) - it would play from there.

**Comment by yash98** [comment]
I think this issue could be closed.

**Comment by yog-singh** [comment]
The intent doesn't list the apps, the file can be accessed from the music player. Video can be played from the intent. I'm using the same device.
