### ISSUE TITLE
Python 2 and 3 compatibility fix was only for initialise

### ISSUE THREAD

**Issue by yash98** [Parth-Vader/MobOff#27]
`if version_info[0] == 2:
        rawinput = raw_input
    else:
        rawinput = input`
In some previous commit this was added to make code compatible for both python 2 and 3 this was done in scope of function initialise only, but this could be done in global scope.

**Comment by Parth-Vader** [comment]
`input` isn't being used in `moboff.download()`, so this isn't a concern. Although I agree this should be global for future purposes.

**Comment by yash98** [comment]
while catching exceptions stated at #25 instead of `secho("run moboff again")` I was actually rewriting moboff_cfg.json with user providing right value at the time of `moboff download`

**Comment by Parth-Vader** [comment]
But if this is done, then there is no need for `initialise`.
