### ISSUE TITLE
Download Playlist feature doesn't send entire playlist to the device.

### ISSUE THREAD

**Issue by yash98** [Parth-Vader/MobOff#29]
Downloading Playlist feature downloads playlist but doesn't push all files to devices. It only selects file with max c time(for multiple max the first one encountered) that is the most recent download. It can be seen in this snippet.
```types = ('*.mp3', '*.mp4', '*.mkv')
    list_of_files = []
    for files in types:
        list_of_files.extend(glob.glob(files))
    recent_download = max(list_of_files,  key=os.path.getctime) # only selects 1 file
    print("File to send : {0}".format(recent_download))```

**Comment by Parth-Vader** [comment]
Are you working on this?

**Comment by yash98** [comment]
Not currently. But I am thinking that the metadata that was fetched could be stored in in a list to obtain file at the time of sending. This is kind of similar to #38 .

**Comment by Parth-Vader** [comment]
Agreed, this data could be used to identify already downloaded files, send several files sequentially too.

**Comment by vishesh98** [comment]
@yash98 so should I work on this issue?

**Comment by yash98** [comment]
sure.
