### ISSUE TITLE
Imports should be PEP-8 compliant

### ISSUE THREAD

**Issue by Parth-Vader** [Parth-Vader/MobOff#36]
See this for reference: https://www.python.org/dev/peps/pep-0008/#imports

**Comment by yash98** [comment]
Import statements have
`from pushbullet import Pushbullet`
and
`import pushbullet`
this was probably done so one could initialise class by `Pushbullet()` instead of `pushbullet.Pushbullet()`. The PEP8 doc doesn't state anything regarding this. The above import statements seem repetitive though.

**Comment by Parth-Vader** [comment]
See the import grouping - that's what I meant.
