### ISSUE TITLE
Detect if a song/file is already downloaded.

### ISSUE THREAD

**Issue by Parth-Vader** [Parth-Vader/MobOff#43]
Then we can prompt the user it's location.

**Comment by yash98** [comment]
It's location? Won't the music file be downloaded to selected folder? We could search the folder itself and tell that its already there.

**Comment by Parth-Vader** [comment]
@yash98 Yes, so by prompting I mean to tell the user it is present in the folder itself and (maybe?) play it if the user wants to. [These](https://stackoverflow.com/questions/307305/play-a-sound-with-python) could be used here, but I'm not really sure of this idea.

**Comment by yash98** [comment]
Playing song through python interpreter seems unnecessary.
