### ISSUE TITLE
help for my idea

### ISSUE THREAD

**Issue by aandroide** [Parth-Vader/MobOff#49]
hello, I'm taking a cue from your project to get me the mp3 file downloaded from youtube dl on my phone using this:
def download(phrase):
    subprocess.Popen(["/usr/bin/youtube-dl",'-o','Music/%(title)s.%(ext)s','--batch-file','lista.txt','--extract-audio','--audio-format=mp3'],stdin=subprocess.PIPE,stdout=subprocess.PIPE)
    say("download della traccia in corso")
   with open(home/pi/Music/file.mp3, "rb") as song:
            file_data = pb.upload_file(song, home/pi/Music/file.mp3)
        push = pb.push_file(**file_data)
I have a youtube url saved in the file list.txt that is recovered from youtube dl and extracts the mp3 file in the Music folder of my raspberry
how should I change this piece of code?
with open(file, "rb") as song:
            file_data = pb.upload_file(song, file)
        push = pb.push_file(**file_data)

I specify that in my py script I have declared my apy key pushbullet and if I insert the title of a single mp3 I will be sent correctly.
what I intend to do is that when the dowload function is called, the process of extracting and sending the mp3 file to my cellphone automatically starts without having to do it programmatically every time

**Comment by Parth-Vader** [comment]
I didn't get your question, what do you mean when you say that you want to send the file automatically in place of programmatically?

**Comment by aandroide** [comment]
hello, I meant that for now I can get the mp3 file, only if I say so ':
with open (home / pi / Music / file.mp3, "rb") as song:
file_data = pb.upload_file (song, home / pi / Music / file.mp3)
push = pb.push_file (** file_data)
while in your script you declared file:
with open(file, "rb") as song:
file_data = pb.upload_file(song, file)
push = pb.push_file(**file_data)
what I wanted to know is how did you declare the file variable that sends the mp3 file just extracted from youtube-dl?
in my case I use the home / pi / Music folder to save the mp3 files extracted from youtube-dl

**Comment by aandroide** [comment]
ok I managed to make it work but only on the files that are in home / pi.
How can I set which files to check are in home / pi / Music?
def download(phrase):
    subprocess.Popen(["/usr/bin/youtube-dl",'-o','Music/%(title)s.%(ext)s','--batch-file','lista.txt','--extract-audio','--audio-format=mp3'],stdin=subprocess.PIPE,stdout=subprocess.PIPE)
    say("download della traccia in corso")
    types = ('*.mp3', '*.mp4', '*.mkv')
    list_of_files = []
    for files in types:
        list_of_files.extend(glob.glob(files))

    recent_download = max(
        list_of_files,
        key=os.path.getctime)

    with open(recent_download, "rb") as song:
        file_data = pb.upload_file(song, recent_download)
    push = pb.push_file(**file_data)

**Comment by aandroide** [comment]
I succeeded, but I would like to eliminate the timer that I had to put in order to wait for the file to be extracted in mp3.
some advice?
this is my script:
def download(phrase):
    subprocess.Popen(["/usr/bin/youtube-dl",'-o','Music/%(title)s.%(ext)s','--batch-file','lista.txt','--extract-audio','--audio-format=mp3','--audio-quality','0'],stdin=subprocess.PIPE,stdout=subprocess.PIPE)
    say("download della traccia in corso")
    time.sleep(100)	# Attende 100 secondi
    types = ('*.mp3', '*.mp4', '*.mkv')
    list_of_files = glob.glob('/home/pi/Music/*.mp3') 
    
    recent_download = max(
        list_of_files,
        key=os.path.getctime)

    with open(recent_download, "rb") as song:
        file_data = pb.upload_file(song, recent_download)
    push = pb.push_file(**file_data)

**Comment by Parth-Vader** [comment]
Cool, I understood your query.
First of all, I store the actual place where I want to put my music files. Then, I create a temp folder and change to that folder. Then I search for `.mp3 or other Video formats` via `glob` and send it to my device. This way, you don't have to search again and again for the most recent downloaded file. 

After successfully sending it to the device, I move the files from the temp folder to the actual folder and delete the temp folder.

I hope you understood my approach.

**Comment by aandroide** [comment]
hi, I think I understand now.
in your script, first download the mp3 file to the temporary folder you create and then send it to the device and delete the folder in order to have a single file in the folder when the file is sent.
correct?
I'm using sdk assistant on raspberry and the download function that I ceato is used to do everything automatically so I'm forced to use the timer since I have to wait for youtube dl to convert the requested file.
I was thinking if I could improve this piece of code but I know that it is the most valid.
Thanks for your help
