### ISSUE TITLE
Missing dependencies file

### ISSUE THREAD

**Issue by ashwani99** [Parth-Vader/MobOff#51]
The project directory is missing a dependency file `requirements.txt`. We should add a dependency file that includes all the dependencies the project needs. Also update the `setup.py` script to read the dependencies from `requirements.txt`

**Comment by Parth-Vader** [comment]
@ashwani99 What additional libraries do you want to include in `requirements.txt` which are not currently inside `setup.py`?

**Comment by ashwani99** [comment]
@Parth-Vader I don't want to add anything extra. I guess it should be better to install `tkinter` and `ffmpef` as you suggested in `README.md` I will update the `setup.py` so that it reads the dependencies directly from `requirements.txt` and dumps it into `install_requires`. Should I go ahead?
