### ISSUE TITLE
Publishing a Docker image to DockerHub

### ISSUE THREAD

**Issue by rajula96reddy** [Parth-Vader/MobOff#61]
This will be a extension to #60 . With a Docker image published to DockerHub, the user should be able to
1. Pull the image
2. Run the container with the `moboff download` flags appended to `docker run` and convert a file at one go without having to install anything else

**Comment by ashwani99** [comment]
So we have to add reference to the image in the `README.md` for this or anything else is required?

**Comment by rajula96reddy** [comment]
Yes, after building an image, and once we publish it on DockerHub, we should add the link to the `README.md`. And we need to have documentation of how to run and convert using the Docker image.
